import java.util.Stack;
import javax.swing.table.DefaultTableModel;


public class calculator_gui extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    public calculator_gui() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        tf_calculation = new javax.swing.JTextField();
        tf_answer = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        btn_clear_history = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        btn_equals = new javax.swing.JButton();
        btn_zero = new javax.swing.JButton();
        btn_dot = new javax.swing.JButton();
        btn_one = new javax.swing.JButton();
        btn_two = new javax.swing.JButton();
        btn_three = new javax.swing.JButton();
        btn_plus = new javax.swing.JButton();
        btn_four = new javax.swing.JButton();
        btn_five = new javax.swing.JButton();
        btn_six = new javax.swing.JButton();
        btn_minus = new javax.swing.JButton();
        btn_seven = new javax.swing.JButton();
        btn_eight = new javax.swing.JButton();
        btn_nine = new javax.swing.JButton();
        btn_mult = new javax.swing.JButton();
        btn_sin = new javax.swing.JButton();
        btn_cos = new javax.swing.JButton();
        btn_tan = new javax.swing.JButton();
        btn_div = new javax.swing.JButton();
        btn_clear = new javax.swing.JButton();
        btn_brack_op = new javax.swing.JButton();
        btn_percentage = new javax.swing.JButton();
        btn_brack_cl = new javax.swing.JButton();
        btn_backspc = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 801, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 675, Short.MAX_VALUE)
        );

        jButton2.setText("jButton2");

        jButton4.setText("jButton3");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton.setText("jButton3");
        jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tf_calculation.setBackground(new java.awt.Color(51, 51, 51));
        tf_calculation.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        tf_calculation.setForeground(new java.awt.Color(255, 255, 255));
        tf_calculation.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tf_calculation.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        tf_calculation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_calculationActionPerformed(evt);
            }
        });

        tf_answer.setEditable(false);
        tf_answer.setBackground(new java.awt.Color(51, 51, 51));
        tf_answer.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        tf_answer.setForeground(new java.awt.Color(255, 255, 255));
        tf_answer.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tf_answer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_answerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tf_answer)
                    .addComponent(tf_calculation))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tf_calculation, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tf_answer, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(102, 102, 102));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));

        btn_clear_history.setBackground(new java.awt.Color(255, 102, 102));
        btn_clear_history.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btn_clear_history.setForeground(new java.awt.Color(255, 255, 255));
        btn_clear_history.setText("Clear");
        btn_clear_history.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btn_clear_history.setBorderPainted(false);
        btn_clear_history.setFocusPainted(false);
        btn_clear_history.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clear_historyActionPerformed(evt);
            }
        });

        jTable1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Expression", "Answer"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setAlignmentX(5.0F);
        jTable1.setGridColor(new java.awt.Color(0, 0, 0));
        jTable1.setRowHeight(30);
        jTable1.setRowMargin(5);
        jTable1.setShowGrid(true);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setBackground(new java.awt.Color(255, 102, 102));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Memory");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(btn_clear_history, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 594, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_clear_history)
                .addGap(12, 12, 12))
        );

        jPanel5.setBackground(new java.awt.Color(102, 102, 102));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btn_equals.setBackground(new java.awt.Color(102, 204, 0));
        btn_equals.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btn_equals.setForeground(new java.awt.Color(255, 255, 255));
        btn_equals.setText("=");
        btn_equals.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_equals.setBorderPainted(false);
        btn_equals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_equalsActionPerformed(evt);
            }
        });

        btn_zero.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btn_zero.setText("0");
        btn_zero.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_zero.setBorderPainted(false);
        btn_zero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_zeroActionPerformed(evt);
            }
        });

        btn_dot.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btn_dot.setForeground(new java.awt.Color(255, 51, 102));
        btn_dot.setText(".");
        btn_dot.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_dot.setBorderPainted(false);
        btn_dot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dotActionPerformed(evt);
            }
        });

        btn_one.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btn_one.setText("1");
        btn_one.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_one.setBorderPainted(false);
        btn_one.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_oneActionPerformed(evt);
            }
        });

        btn_two.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btn_two.setText("2");
        btn_two.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_two.setBorderPainted(false);
        btn_two.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_twoActionPerformed(evt);
            }
        });

        btn_three.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btn_three.setText("3");
        btn_three.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_three.setBorderPainted(false);
        btn_three.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_threeActionPerformed(evt);
            }
        });

        btn_plus.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btn_plus.setForeground(new java.awt.Color(255, 51, 102));
        btn_plus.setText("+");
        btn_plus.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_plus.setBorderPainted(false);
        btn_plus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_plusActionPerformed(evt);
            }
        });

        btn_four.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btn_four.setText("4");
        btn_four.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_four.setBorderPainted(false);
        btn_four.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_fourActionPerformed(evt);
            }
        });

        btn_five.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btn_five.setText("5");
        btn_five.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_five.setBorderPainted(false);
        btn_five.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_fiveActionPerformed(evt);
            }
        });

        btn_six.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btn_six.setText("6");
        btn_six.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_six.setBorderPainted(false);
        btn_six.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sixActionPerformed(evt);
            }
        });

        btn_minus.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btn_minus.setForeground(new java.awt.Color(255, 51, 102));
        btn_minus.setText("-");
        btn_minus.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_minus.setBorderPainted(false);
        btn_minus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_minusActionPerformed(evt);
            }
        });

        btn_seven.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btn_seven.setText("7");
        btn_seven.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, null, new java.awt.Color(255, 255, 255), null, null));
        btn_seven.setBorderPainted(false);
        btn_seven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sevenActionPerformed(evt);
            }
        });

        btn_eight.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btn_eight.setText("8");
        btn_eight.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_eight.setBorderPainted(false);
        btn_eight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eightActionPerformed(evt);
            }
        });

        btn_nine.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btn_nine.setText("9");
        btn_nine.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btn_nine.setBorderPainted(false);
        btn_nine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nineActionPerformed(evt);
            }
        });

        btn_mult.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btn_mult.setForeground(new java.awt.Color(255, 51, 102));
        btn_mult.setText("×");
        btn_mult.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_mult.setBorderPainted(false);
        btn_mult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_multActionPerformed(evt);
            }
        });

        btn_sin.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btn_sin.setText("sin");
        btn_sin.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_sin.setBorderPainted(false);

        btn_cos.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btn_cos.setText("cos");
        btn_cos.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_cos.setBorderPainted(false);

        btn_tan.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btn_tan.setText("tan");
        btn_tan.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_tan.setBorderPainted(false);

        btn_div.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btn_div.setForeground(new java.awt.Color(255, 51, 102));
        btn_div.setText("÷");
        btn_div.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_div.setBorderPainted(false);
        btn_div.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_divActionPerformed(evt);
            }
        });

        btn_clear.setBackground(new java.awt.Color(255, 102, 102));
        btn_clear.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btn_clear.setForeground(new java.awt.Color(255, 255, 255));
        btn_clear.setText("C");
        btn_clear.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_clear.setBorderPainted(false);
        btn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearActionPerformed(evt);
            }
        });

        btn_brack_op.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btn_brack_op.setForeground(new java.awt.Color(255, 51, 102));
        btn_brack_op.setText("(");
        btn_brack_op.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_brack_op.setBorderPainted(false);
        btn_brack_op.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_brack_opActionPerformed(evt);
            }
        });

        btn_percentage.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btn_percentage.setForeground(new java.awt.Color(255, 51, 102));
        btn_percentage.setText("%");
        btn_percentage.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_percentage.setBorderPainted(false);
        btn_percentage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_percentageActionPerformed(evt);
            }
        });

        btn_brack_cl.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btn_brack_cl.setForeground(new java.awt.Color(255, 51, 102));
        btn_brack_cl.setText(")");
        btn_brack_cl.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_brack_cl.setBorderPainted(false);
        btn_brack_cl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_brack_clActionPerformed(evt);
            }
        });

        btn_backspc.setBackground(new java.awt.Color(255, 102, 102));
        btn_backspc.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn_backspc.setForeground(new java.awt.Color(255, 255, 255));
        btn_backspc.setText("BACK");
        btn_backspc.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_backspc.setBorderPainted(false);
        btn_backspc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backspcActionPerformed(evt);
            }
        });
        btn_backspc.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                btn_backspcPropertyChange(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn_one, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_percentage, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(btn_two, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_three, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_plus, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(btn_zero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_dot, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_equals, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(btn_seven, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_eight, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_nine, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_mult, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(btn_sin, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_cos, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_tan, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_div, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                                .addComponent(btn_four, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_five, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_six, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_minus, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(btn_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_backspc, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(23, 23, 23)
                                .addComponent(btn_brack_op, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_brack_cl, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(19, 19, 19))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_brack_op, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_brack_cl, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn_backspc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_sin, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_cos, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_tan, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_div, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_seven, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_eight, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_nine, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_mult, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_four, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_five, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_six, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_minus, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_one, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_two, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_three, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_plus, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_zero, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_dot, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_percentage, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn_equals, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonActionPerformed

    private void btn_divActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_divActionPerformed
       String get_previous;
       // If there is previous answer take it and make it the new input if / operation is used      
        if (tf_answer.getText().isEmpty()){
            get_previous = tf_calculation.getText();
            get_previous += "/";
            tf_calculation.setText(get_previous);           
        }
        else{
           get_previous = tf_answer.getText();
           get_previous += "/";
           tf_calculation.setText(get_previous); 
           tf_answer.setText("");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_divActionPerformed

    private void btn_plusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_plusActionPerformed
       String get_previous;
       // If there is previous answer take it and make it the new input if + operation is used      
        if (tf_answer.getText().isEmpty()){
            get_previous = tf_calculation.getText();
            get_previous += "+";
            tf_calculation.setText(get_previous);           
        }
        else{
           get_previous = tf_answer.getText();
           get_previous += "+";
           tf_calculation.setText(get_previous); 
           tf_answer.setText("");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btn_plusActionPerformed

    private void btn_clear_historyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clear_historyActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
    }//GEN-LAST:event_btn_clear_historyActionPerformed

    private void btn_oneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_oneActionPerformed
       String get_previous;
       get_previous = tf_calculation.getText();
       get_previous = get_previous+"1";
       tf_calculation.setText(get_previous);
    }//GEN-LAST:event_btn_oneActionPerformed

    private void btn_zeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_zeroActionPerformed
       String get_previous;
       get_previous = tf_calculation.getText();
        if (get_previous.length() != 0){
           char last_char = get_previous.charAt(get_previous.length()-1);
            if (last_char == '/'){
                tf_answer.setText("Error: Division by Zero");
            }
            else{
                get_previous += "0";
            }           
        }
        else{
           get_previous += "0";
        }
       tf_calculation.setText(get_previous);
    }//GEN-LAST:event_btn_zeroActionPerformed

    private void btn_twoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_twoActionPerformed
       String get_previous;
       get_previous = tf_calculation.getText();
       get_previous = get_previous+"2";
       tf_calculation.setText(get_previous);        // TODO add your handling code here:
    }//GEN-LAST:event_btn_twoActionPerformed

    private void btn_threeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_threeActionPerformed
       String get_previous;
       get_previous = tf_calculation.getText();
       get_previous = get_previous+"3";
       tf_calculation.setText(get_previous);        // TODO add your handling code here:
    }//GEN-LAST:event_btn_threeActionPerformed

    private void btn_fourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_fourActionPerformed
       String get_previous;
       get_previous = tf_calculation.getText();
       get_previous = get_previous+"4";
       tf_calculation.setText(get_previous);        // TODO add your handling code here:
    }//GEN-LAST:event_btn_fourActionPerformed

    private void btn_fiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_fiveActionPerformed
       String get_previous;
       get_previous = tf_calculation.getText();
       get_previous = get_previous+"5";
       tf_calculation.setText(get_previous);        // TODO add your handling code here:
    }//GEN-LAST:event_btn_fiveActionPerformed

    private void btn_sixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sixActionPerformed
       String get_previous;
       get_previous = tf_calculation.getText();
       get_previous = get_previous+"6";
       tf_calculation.setText(get_previous);        // TODO add your handling code here:
    }//GEN-LAST:event_btn_sixActionPerformed

    private void btn_sevenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sevenActionPerformed
       String get_previous;
       get_previous = tf_calculation.getText();
       get_previous = get_previous+"7";
       tf_calculation.setText(get_previous);        // TODO add your handling code here:
    }//GEN-LAST:event_btn_sevenActionPerformed

    private void btn_eightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eightActionPerformed
       String get_previous;
       get_previous = tf_calculation.getText();
       get_previous = get_previous+"8";
       tf_calculation.setText(get_previous);        // TODO add your handling code here:
    }//GEN-LAST:event_btn_eightActionPerformed

    private void btn_nineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nineActionPerformed
       String get_previous;
       get_previous = tf_calculation.getText();
       get_previous = get_previous+"9";
       tf_calculation.setText(get_previous);        // TODO add your handling code here:
    }//GEN-LAST:event_btn_nineActionPerformed

    private void btn_minusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_minusActionPerformed
       String get_previous;
       // If there is previous answer take it and make it the new input if - operation is used
        if (tf_answer.getText().isEmpty()){
            get_previous = tf_calculation.getText();
            get_previous += "-";
            tf_calculation.setText(get_previous);           
        }
        else{
           get_previous = tf_answer.getText();
           get_previous += "-";
           tf_calculation.setText(get_previous); 
           tf_answer.setText("");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btn_minusActionPerformed

    private void btn_multActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_multActionPerformed
       String get_previous;   
        // If there is previous answer take it and make it the new input if * operation is used
        if (tf_answer.getText().isEmpty()){
            get_previous = tf_calculation.getText();
            get_previous += "*";
            tf_calculation.setText(get_previous);           
        }
        else{
           get_previous = tf_answer.getText();
           get_previous += "*";
           tf_calculation.setText(get_previous); 
           tf_answer.setText("");
        }         // TODO add your handling code here:
    }//GEN-LAST:event_btn_multActionPerformed

    private void btn_dotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dotActionPerformed
       String get_previous;
       get_previous = tf_calculation.getText();
       get_previous = get_previous+".";
       tf_calculation.setText(get_previous);        // TODO add your handling code here:
    }//GEN-LAST:event_btn_dotActionPerformed

    private void btn_brack_opActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_brack_opActionPerformed
        String get_previous;
       // If there is previous answer take it and make it the new input if ( operation is used
        if (tf_answer.getText().isEmpty()){
            get_previous = tf_calculation.getText();
            if (get_previous.length() != 0){
                char last_char = get_previous.charAt(get_previous.length()-1);
                if (last_char == '*' || last_char == '/' || last_char == '+' || last_char == '-'){
                    get_previous += "(";
                }
                else{
                    get_previous += "*(";
                }           
            }
            else{
                get_previous += "(";
            }
        }
        else{
            get_previous = tf_answer.getText();
            get_previous += "*(";   
            tf_answer.setText("");
        }
        tf_calculation.setText(get_previous);
                        // TODO add your handling code here:
    }//GEN-LAST:event_btn_brack_opActionPerformed

    private void btn_brack_clActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_brack_clActionPerformed
       String get_previous;
       get_previous = tf_calculation.getText();
       get_previous = get_previous+")";
       tf_calculation.setText(get_previous);        // TODO add your handling code here:
    }//GEN-LAST:event_btn_brack_clActionPerformed

    private void btn_percentageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_percentageActionPerformed
        String get_previous;
        // If there is previous answer take it and make it the new input if + operation is used      
        if (tf_answer.getText().isEmpty()){
            get_previous = tf_calculation.getText();
            get_previous += "%";
            tf_calculation.setText(get_previous);           
        }
        else{
           get_previous = tf_answer.getText();
           get_previous += "%";
           tf_calculation.setText(get_previous); 
           tf_answer.setText("");
        }         // TODO add your handling code here:
    }//GEN-LAST:event_btn_percentageActionPerformed

    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
       String get_previous;
       get_previous = tf_calculation.getText();
       get_previous = "";
       tf_calculation.setText(get_previous);
       tf_answer.setText("");                      // TODO add your handling code here:
    }//GEN-LAST:event_btn_clearActionPerformed

    private void tf_calculationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_calculationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_calculationActionPerformed

    private void tf_answerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_answerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_answerActionPerformed

    private void btn_equalsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_equalsActionPerformed
        // TODO add your handling code here:
        String get_expression = tf_calculation.getText();
        // Dealing with the first character being - or +
        char first_char = get_expression.charAt(0);
        if (first_char == '-' || first_char == '+'){
            get_expression = '0' + get_expression;
        }        
        
        if (isValidExpression(get_expression)) {
            // Process the expression to handle '%'
            get_expression = handlePercentage(get_expression);
            // Calculate the result and display it
            double result = do_calculation(get_expression);
            tf_answer.setText(Double.toString(result));
        } 
        else {
            // Display error message for invalid input
            tf_answer.setText("Value Error: Invalid Input");
        }  

        // Inserting into the table
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[] {tf_calculation.getText(), tf_answer.getText()});        
    }//GEN-LAST:event_btn_equalsActionPerformed

    // Validate the string, if theire is letters or unwanted characters raise an error
    public static boolean isValidExpression(String expression) {
        for (int i = 0; i < expression.length(); i++) {
            char c = expression.charAt(i);
            if (!(Character.isDigit(c) || c == '/' || c == '*' || c == '+' || c == '-' || c == '%' || c == '(' || c == ')' || c == '.')) {
                return false;
            }
        }
        return true;
    }    
    
    // Handling percentage sign
    public static String handlePercentage(String expression) {
        StringBuilder modifiedExpression = new StringBuilder();
        for (int j = 0; j < expression.length(); j++) {
            char currentChar = expression.charAt(j);
            if (currentChar == '%') {
                // Find the digits preceding the '%'
                StringBuilder digits = new StringBuilder();
                int x = j - 1;
                while (x >= 0 && (Character.isDigit(expression.charAt(x)) || expression.charAt(x) == '.')) {
                    digits.append(expression.charAt(x));
                    x--;
                }
                // Append the division expression with parentheses (digits/100)
                modifiedExpression.replace(x+1, currentChar, "(" + digits.reverse() + "/100)");
            } else {
                modifiedExpression.append(currentChar);
            }
        }
        return modifiedExpression.toString();
    }
    
    public static double do_calculation(String str) {
        Stack<Double> numberStack = new Stack<>();
        Stack<Character> operatorStack = new Stack<>();
        // BODMAS rules applied
        for (int i = 0; i < str.length(); i++) {
            char c = str.charAt(i);
            if (c == '(') {
                operatorStack.push(c);
            } 
            else if (c == ')') {
                while (!operatorStack.isEmpty() && operatorStack.peek() != '(') {
                    char operator = operatorStack.pop();
                    double num2 = numberStack.pop();
                    double num1 = numberStack.pop();
                    numberStack.push(applyOperation(operator, num1, num2));
                }
                if (!operatorStack.isEmpty()) {
                    operatorStack.pop(); // Remove the '('
                }
            } 
            else if (isOperator(c)) {
                while (!operatorStack.isEmpty() && precedence(c) <= precedence(operatorStack.peek())) {
                    char operator = operatorStack.pop();
                    double num2 = numberStack.pop();
                    double num1 = numberStack.pop();
                    numberStack.push(applyOperation(operator, num1, num2));
                }
                operatorStack.push(c);
            } 
            else if (Character.isDigit(c) || c == '.') {
                int start = i;
                while (i + 1 < str.length() && (Character.isDigit(str.charAt(i + 1)) || str.charAt(i + 1) == '.')) {
                    i++;
                }
                double num = Double.parseDouble(str.substring(start, i + 1));
                numberStack.push(num);
            }
        }

        while (!operatorStack.isEmpty()) {
            char operator = operatorStack.pop();
            double num2 = numberStack.pop();
            double num1 = numberStack.pop();
            numberStack.push(applyOperation(operator, num1, num2));
        }

        return numberStack.pop();
    }

    public static boolean isOperator(char c) {
        return c == '+' || c == '-' || c == '*' || c == '/';
    }

    public static int precedence(char c) {
        switch (c) {
            case '+':
            case '-':
                return 1;
            case '*':
            case '/':
                return 2;
            default:
                return 0;
        }
    }

    public static double applyOperation(char operator, double a, double b) {
        switch (operator) {
            case '+':
                return a + b;
            case '-':
                return a - b;
            case '*':
                return a * b;
            case '/':
                return a / b;
            default:
                // IllegalArgumentException is a type of exception that indicates 
                // that a method has been passed an illegal or inappropriate argument.
                // In here, i am using it so that i don't have an error since switch needs a default value
                // I have taken care of invalid input in the beginning of this method/function.
                throw new IllegalArgumentException("Invalid operator: " + operator);
                
        }
    }
    
    private void btn_backspcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backspcActionPerformed
        String get_previous = tf_calculation.getText();
        if (get_previous.length()>0) {
            String newText = get_previous.substring(0, get_previous.length()-1);
            tf_calculation.setText(newText);
        }
    }//GEN-LAST:event_btn_backspcActionPerformed

    private void btn_backspcPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_btn_backspcPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_backspcPropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(calculator_gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(calculator_gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(calculator_gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(calculator_gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new calculator_gui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_backspc;
    private javax.swing.JButton btn_brack_cl;
    private javax.swing.JButton btn_brack_op;
    private javax.swing.JButton btn_clear;
    private javax.swing.JButton btn_clear_history;
    private javax.swing.JButton btn_cos;
    private javax.swing.JButton btn_div;
    private javax.swing.JButton btn_dot;
    private javax.swing.JButton btn_eight;
    private javax.swing.JButton btn_equals;
    private javax.swing.JButton btn_five;
    private javax.swing.JButton btn_four;
    private javax.swing.JButton btn_minus;
    private javax.swing.JButton btn_mult;
    private javax.swing.JButton btn_nine;
    private javax.swing.JButton btn_one;
    private javax.swing.JButton btn_percentage;
    private javax.swing.JButton btn_plus;
    private javax.swing.JButton btn_seven;
    private javax.swing.JButton btn_sin;
    private javax.swing.JButton btn_six;
    private javax.swing.JButton btn_tan;
    private javax.swing.JButton btn_three;
    private javax.swing.JButton btn_two;
    private javax.swing.JButton btn_zero;
    private javax.swing.JButton jButton;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField tf_answer;
    private javax.swing.JTextField tf_calculation;
    // End of variables declaration//GEN-END:variables
}
